# -*- coding: utf-8 -*-
"""day_4_9-7-2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ivpob-c1SzjO6T_g9nBWnksYb7ELSi2
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/complete_renewable_energy_dataset.csv")

print("First 5 Rows")
print(df.head())

print("\nLast 5 Rows")
print(df.tail())

print("\nShape of Dataset")
print(df.shape)

print("\nColumns")
print(df.columns)

print("\nDataset Information")
print(df.info())

print("\nStatistical Summary")
print(df.describe())

print("\nNull Values")
print(df.isnull().sum())

numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    df[col].fillna(df[col].mean(), inplace=True)

# Fill categorical columns with mode

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

print("\nNull Values After Cleaning")
print(df.isnull().sum())

print("\nCorrelation Matrix")

correlation = df.corr(numeric_only=True)

print(correlation)

print("\nDuplicate Rows :", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print(df.head())

print(df.describe())

df.to_csv("cleaned_sustainability_dataset.csv", index=False)

print("\nClean dataset saved successfully.")

print("""

SUMMARY

1. Imported the sustainability dataset.
2. Displayed dataset information.
3. Checked rows, columns and data types.
4. Generated statistical summary.
5. Identified missing values.
6. Filled numeric null values using mean.
7. Filled categorical null values using mode.
8. Removed duplicate records.
9. Analysed relationships using correlation.
10. Saved the cleaned dataset.

Conclusion:
The dataset was cleaned successfully and basic exploratory data
analysis was performed. Feature relationships were examined using
correlation, and the dataset is now ready for further analysis or
machine learning.

""")