# -*- coding: utf-8 -*-
"""day 2 python assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ct95dIjc8NdEWRo0PVM3Juf2gKcsHPyB
"""

print("----- Dictionary Methods -----")

student = {"name": "Virendra", "age": 20, "course": "Python"}

print(student.keys())
print(student.values())
print(student.items())

student.update({"city": "Nashik"})
print(student)

student.pop("age")
print(student)

print("\n----- List Methods -----")

numbers = [10, 20, 30]

numbers.append(40)
numbers.extend([50, 60])
numbers.insert(1, 15)
numbers.remove(30)
numbers.sort()

print(numbers)

print("\n----- Tuple Methods -----")

t = (10, 20, 30, 20, 40)

print(len(t))
print(max(t))
print(min(t))
print(t.count(20))
print(t.index(30))

print("\n----- Set Methods -----")

s = {10, 20, 30}

s.add(40)
s.update([50, 60])
s.remove(20)
s.discard(100)
print(s)

s.clear()
print(s)

print("\n----- If Statement -----")

age = 18

if age >= 18:
    print("You are eligible to vote.")

print("\n----- If-Else -----")

num = 7

if num % 2 == 0:
    print("Even Number")
else:
    print("Odd Number")

print("\n----- If-Elif-Else -----")

marks = 82

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
else:
    print("Grade C")

print("\n----- Nested If -----")

age = 22
license = True

if age >= 18:
    if license:
        print("You can drive.")
    else:
        print("Get a driving license.")
else:
    print("You are underage.")

print("\n----- Break -----")

for i in range(1, 11):
    if i == 6:
        break
    print(i)

print("\n----- Continue -----")

for i in range(1, 6):
    if i == 3:
        continue
    print(i)

print("\n----- Pass -----")

for i in range(1, 4):
    if i == 2:
        pass
    print(i)

print("\n----- Input -----")

name = input("Enter your name: ")
print("Welcome,", name)

print("\n----- Range -----")

for i in range(1, 6):
    print(i)

print("\n----- Len -----")

fruits = ["Apple", "Banana", "Mango"]
print("Length:", len(fruits))

print("\n----- Type -----")

x = 100
print(type(x))

print("\n----- For Loop -----")

for i in range(5):
    print(i)

print("\n----- While Loop -----")

count = 1

while count <= 5:
    print(count)
    count += 1

print("\nAssignment Completed!")