# -*- coding: utf-8 -*-
"""day_3_8-7-2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvaOgQon0VfCzsPww7DsYo6BnLWsb0NY
"""

import numpy as np

print("========== NUMPY ASSIGNMENT ==========\n")

# Create 1D Array
arr1 = np.array([10, 20, 30, 40, 50])

# Create 2D Array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create 3D Array
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\n3D Array:")
print(arr3)

# Indexing
print("\n----- INDEXING -----")
print("arr1[0] =", arr1[0])
print("arr1[-1] =", arr1[-1])
print("arr2[1][2] =", arr2[1][2])
print("arr2[2][0] =", arr2[2][0])
print("arr3[1][0][1] =", arr3[1][0][1])

# Mathematical Operations
print("\n----- MATHEMATICAL OPERATIONS -----")
print("Addition:\n", arr2 + 10)
print("Subtraction:\n", arr2 - 2)
print("Multiplication:\n", arr2 * 2)
print("Division:\n", arr2 / 2)
print("Square:\n", arr2 ** 2)

# NumPy Methods
print("\n----- NUMPY METHODS -----")

print("1. ndim =", arr2.ndim)
print("2. shape =", arr2.shape)
print("3. size =", arr2.size)
print("4. dtype =", arr2.dtype)

print("\n5. reshape")
print(arr2.reshape(1, 9))

print("\n6. flatten")
print(arr2.flatten())

print("\n7. transpose")
print(arr2.T)

print("\n8. sum =", np.sum(arr2))
print("9. mean =", np.mean(arr2))
print("10. max =", np.max(arr2))
print("11. min =", np.min(arr2))
print("12. argmax =", np.argmax(arr2))
print("13. argmin =", np.argmin(arr2))

print("\n14. sqrt")
print(np.sqrt(arr2))

print("\n15. sort")
print(np.sort(np.array([8, 2, 6, 1, 9, 4])))

print("\n16. unique")
print(np.unique(np.array([1, 2, 2, 3, 4, 4, 5])))

print("\n17. concatenate")
print(np.concatenate((arr1, np.array([60, 70]))))

print("\n18. zeros")
print(np.zeros((2, 3)))

print("\n19. ones")
print(np.ones((2, 3)))

print("\n20. identity matrix")
print(np.eye(3))

print("\nAssignment Completed Successfully!")